
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BubbleCfg : Luban.BeanBase
{
    public BubbleCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["probability"]; }
        { if(!_buf["anim_name"].IsString) { throw new SerializationException(); }  AnimName = _buf["anim_name"]; }
    }

    public static BubbleCfg DeserializeBubbleCfg(JSONNode _buf)
    {
        return new BubbleCfg(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 概率
    /// </summary>
    public readonly float Probability;
    /// <summary>
    /// 动画名称
    /// </summary>
    public readonly string AnimName;
   
    public const int __ID__ = -1593010152;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "probability:" + Probability + ","
        + "animName:" + AnimName + ","
        + "}";
    }
}

}

