
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class FishSpwanGroup : Luban.BeanBase
{
    public FishSpwanGroup(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["bubble_id"].IsNumber) { throw new SerializationException(); }  BubbleId = _buf["bubble_id"]; }
        { if(!_buf["reachable_depth"].IsNumber) { throw new SerializationException(); }  ReachableDepth = _buf["reachable_depth"]; }
        { if(!_buf["probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["probability"]; }
        { var __json0 = _buf["fish_ids"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; FishIds = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FishIds[__index0++] = __v0; }   }
    }

    public static FishSpwanGroup DeserializeFishSpwanGroup(JSONNode _buf)
    {
        return new FishSpwanGroup(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 气泡类型id
    /// </summary>
    public readonly int BubbleId;
    /// <summary>
    /// 可达到的深度（1,2,3）
    /// </summary>
    public readonly int ReachableDepth;
    /// <summary>
    /// 概率
    /// </summary>
    public readonly float Probability;
    /// <summary>
    /// 对应鱼类id
    /// </summary>
    public readonly int[] FishIds;
   
    public const int __ID__ = -1366008848;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "bubbleId:" + BubbleId + ","
        + "reachableDepth:" + ReachableDepth + ","
        + "probability:" + Probability + ","
        + "fishIds:" + Luban.StringUtil.CollectionToString(FishIds) + ","
        + "}";
    }
}

}

