
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class FishCfg : Luban.BeanBase
{
    public FishCfg(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["cost"].IsNumber) { throw new SerializationException(); }  Cost = _buf["cost"]; }
        { if(!_buf["sprite_path"].IsString) { throw new SerializationException(); }  SpritePath = _buf["sprite_path"]; }
        { if(!_buf["name_sprite_path"].IsString) { throw new SerializationException(); }  NameSpritePath = _buf["name_sprite_path"]; }
        { if(!_buf["cost_sprite_path"].IsString) { throw new SerializationException(); }  CostSpritePath = _buf["cost_sprite_path"]; }
    }

    public static FishCfg DeserializeFishCfg(JSONNode _buf)
    {
        return new FishCfg(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 鱼名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价值
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 鱼图像路径
    /// </summary>
    public readonly string SpritePath;
    /// <summary>
    /// 鱼名图像路径
    /// </summary>
    public readonly string NameSpritePath;
    /// <summary>
    /// 鱼价值图像路径
    /// </summary>
    public readonly string CostSpritePath;
   
    public const int __ID__ = 816179916;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "cost:" + Cost + ","
        + "spritePath:" + SpritePath + ","
        + "nameSpritePath:" + NameSpritePath + ","
        + "costSpritePath:" + CostSpritePath + ","
        + "}";
    }
}

}

