
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;
using Cysharp.Threading.Tasks;

namespace cfg
{
public partial class Tables
{
    public TbBubbleCfg TbBubbleCfg {get;private set; }
    public TbFishCfg TbFishCfg {get;private set; }
    public TbFishSpwanGroup TbFishSpwanGroup {get;private set; }

    public Tables()
    {
    }

    public void Init(System.Func<string, JSONNode> loader)
    {
        TbBubbleCfg = new TbBubbleCfg(loader("tbbubblecfg"));
        TbFishCfg = new TbFishCfg(loader("tbfishcfg"));
        TbFishSpwanGroup = new TbFishSpwanGroup(loader("tbfishspwangroup"));
        ResolveRef();
    }

    public async UniTask Init(System.Func<string, UniTask<JSONNode>> loader)
    {
        TbBubbleCfg = new TbBubbleCfg(await loader("tbbubblecfg"));
        TbFishCfg = new TbFishCfg(await loader("tbfishcfg"));
        TbFishSpwanGroup = new TbFishSpwanGroup(await loader("tbfishspwangroup"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBubbleCfg.ResolveRef(this);
        TbFishCfg.ResolveRef(this);
        TbFishSpwanGroup.ResolveRef(this);
    }
}

}
