
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbBubbleCfg TbBubbleCfg {get; }
    public TbFishCfg TbFishCfg {get; }
    public TbFishSpwanGroup TbFishSpwanGroup {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbBubbleCfg = new TbBubbleCfg(loader("tbbubblecfg"));
        TbFishCfg = new TbFishCfg(loader("tbfishcfg"));
        TbFishSpwanGroup = new TbFishSpwanGroup(loader("tbfishspwangroup"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBubbleCfg.ResolveRef(this);
        TbFishCfg.ResolveRef(this);
        TbFishSpwanGroup.ResolveRef(this);
    }
}

}
