
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBubbleCfg
{
    private readonly System.Collections.Generic.Dictionary<int, BubbleCfg> _dataMap;
    private readonly System.Collections.Generic.List<BubbleCfg> _dataList;
    
    public TbBubbleCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BubbleCfg>();
        _dataList = new System.Collections.Generic.List<BubbleCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BubbleCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = BubbleCfg.DeserializeBubbleCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BubbleCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<BubbleCfg> DataList => _dataList;

    public BubbleCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BubbleCfg Get(int key) => _dataMap[key];
    public BubbleCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

