
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbFishCfg
{
    private readonly System.Collections.Generic.Dictionary<int, FishCfg> _dataMap;
    private readonly System.Collections.Generic.List<FishCfg> _dataList;
    
    public TbFishCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, FishCfg>();
        _dataList = new System.Collections.Generic.List<FishCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            FishCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = FishCfg.DeserializeFishCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, FishCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<FishCfg> DataList => _dataList;

    public FishCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FishCfg Get(int key) => _dataMap[key];
    public FishCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

